version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - mongo
    tty: true

  mongo:
    image: mongo:3.2
    ports:
      - 27017:27017
    # Optionally mount external data directory
    volumes:
      - ~/data3.2:/data/db

  mysql:
      image: mysql:5.7
      volumes:
        - mysql_data: ~/keycloak_data/vol
      environment:
        # Change root password for a stronger one
        MYSQL_ROOT_PASSWORD: root
        # Change this seetings
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password

  keycloak:
      image: jboss/keycloak
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: mysql
        # Same values than the ones declared in mysql service.
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        # Change this seetings
        KEYCLOAK_USER: admin # VERY IMPORTANT!
        KEYCLOAK_PASSWORD: Pa55w0rd  # VERY IMPORTANT!
        DB_VENDOR: MYSQL
        # Uncomment the line below if you want to specify JDBC parameters.
        # The parameter below is just an example, and it shouldn't be used in production without knowledge.
        # It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "connectTimeout=30000"
      ports:
        - 8080:8080
      depends_on:
        - mysql